<a href="https://colab.research.google.com/github/Ananassio/Data-Minig-Lab/blob/main/Week_3/Assignment_3.1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment I: Numpy

Perform the follwing tasks:


In [2]:
#1: import the numpy library
import numpy as np

In [4]:
#2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.16283014, 0.44311343, 0.69248342, 0.2441419 , 0.11612559,
        0.00718727, 0.45223848, 0.139204  , 0.86211054, 0.17739877],
       [0.70542736, 0.42601827, 0.69345335, 0.11220117, 0.0988888 ,
        0.21442613, 0.57352005, 0.79341731, 0.46085964, 0.12506859],
       [0.06853254, 0.36640894, 0.99538094, 0.25273165, 0.30720955,
        0.6139022 , 0.30557665, 0.23981776, 0.4370761 , 0.8476155 ],
       [0.3735852 , 0.13817403, 0.95697193, 0.38549952, 0.60727766,
        0.04906026, 0.08394005, 0.57527443, 0.70628771, 0.91059148],
       [0.81129931, 0.02373053, 0.97165334, 0.19157936, 0.40674595,
        0.02432413, 0.88462812, 0.63621569, 0.0219766 , 0.26560092],
       [0.35609825, 0.86788371, 0.58044475, 0.18508144, 0.88372495,
        0.46321255, 0.98526954, 0.43161846, 0.33761462, 0.44432289],
       [0.06368299, 0.82512327, 0.80134185, 0.02089083, 0.87772739,
        0.98625534, 0.27891653, 0.74300858, 0.62996547, 0.85510335],
       [0.38593383, 0.07143022, 0.9965813

In [9]:
#3: return only the odd rows of A
A[::2]

array([[0.16283014, 0.44311343, 0.69248342, 0.2441419 , 0.11612559,
        0.00718727, 0.45223848, 0.139204  , 0.86211054, 0.17739877],
       [0.06853254, 0.36640894, 0.99538094, 0.25273165, 0.30720955,
        0.6139022 , 0.30557665, 0.23981776, 0.4370761 , 0.8476155 ],
       [0.81129931, 0.02373053, 0.97165334, 0.19157936, 0.40674595,
        0.02432413, 0.88462812, 0.63621569, 0.0219766 , 0.26560092],
       [0.06368299, 0.82512327, 0.80134185, 0.02089083, 0.87772739,
        0.98625534, 0.27891653, 0.74300858, 0.62996547, 0.85510335],
       [0.47738712, 0.04807   , 0.46314947, 0.81323022, 0.24819398,
        0.36529393, 0.96334969, 0.99541267, 0.4841641 , 0.84872836]])

In [11]:
#4: perform a matrix multiplication of A with it's transposed
A*A.transpose()

array([[0.02651365, 0.31258433, 0.04745765, 0.0912078 , 0.09421261,
        0.00255937, 0.0287999 , 0.05372353, 0.41156046, 0.00259328],
       [0.31258433, 0.18149157, 0.25408751, 0.01550329, 0.00234668,
        0.18609695, 0.47322474, 0.05667397, 0.02215352, 0.04732884],
       [0.04745765, 0.25408751, 0.99078322, 0.2418571 , 0.29850118,
        0.35633631, 0.24487136, 0.2389979 , 0.20243156, 0.04231531],
       [0.0912078 , 0.01550329, 0.2418571 , 0.14860988, 0.11634187,
        0.00908014, 0.00175358, 0.37335462, 0.57437451, 0.69012153],
       [0.09421261, 0.00234668, 0.29850118, 0.11634187, 0.16544227,
        0.02149584, 0.77646233, 0.56180931, 0.00545446, 0.12432812],
       [0.00255937, 0.18609695, 0.35633631, 0.00908014, 0.02149584,
        0.21456587, 0.97172735, 0.33053748, 0.12332857, 0.11068344],
       [0.0287999 , 0.47322474, 0.24487136, 0.00175358, 0.77646233,
        0.97172735, 0.07779443, 0.19596322, 0.60687705, 0.63727304],
       [0.05372353, 0.05667397, 0.2389979

In [13]:
#5: compute the matrix inverse of A
np.linalg.inv(A)

array([[-1.70398362,  2.85072248, -0.24564407, -0.313126  ,  1.19075281,
        -1.74873881,  0.26158115,  0.36798465, -2.39164489,  2.73809793],
       [-0.87443584,  1.20452599,  1.63147821,  1.36351751, -3.32053794,
         3.45349617, -2.63771629, -0.08505352,  0.76014568, -1.80836065],
       [ 0.70533452, -0.77537293,  1.00860701,  0.4295385 , -0.73778255,
         1.25266713, -1.04882365,  0.1900009 ,  0.78392231, -1.76163001],
       [-0.09651858,  0.24178272,  1.19709691,  1.11584115, -3.75709446,
         3.54147797, -3.44236049,  1.24312867,  1.90722829, -2.58330266],
       [ 0.34177413, -1.01197887, -1.33326224,  0.19848031,  0.66351743,
         0.12247239,  0.69740242,  0.44633428, -0.25988537,  0.06316139],
       [-0.14873266,  0.69567592, -0.18884746, -1.6672503 ,  1.07676931,
        -1.83810964,  1.3577949 ,  0.675836  , -0.87317849,  1.35341746],
       [ 0.7784979 , -1.03021286, -0.49941769, -1.13439421,  1.96680718,
        -1.1226073 ,  1.2857519 , -0.56392225

In [17]:
#6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
np.where(A < 0.5,A, A/2 )

array([[0.16283014, 0.44311343, 0.34624171, 0.2441419 , 0.11612559,
        0.00718727, 0.45223848, 0.139204  , 0.43105527, 0.17739877],
       [0.35271368, 0.42601827, 0.34672667, 0.11220117, 0.0988888 ,
        0.21442613, 0.28676002, 0.39670865, 0.46085964, 0.12506859],
       [0.06853254, 0.36640894, 0.49769047, 0.25273165, 0.30720955,
        0.3069511 , 0.30557665, 0.23981776, 0.4370761 , 0.42380775],
       [0.3735852 , 0.13817403, 0.47848597, 0.38549952, 0.30363883,
        0.04906026, 0.08394005, 0.28763721, 0.35314386, 0.45529574],
       [0.40564965, 0.02373053, 0.48582667, 0.19157936, 0.40674595,
        0.02432413, 0.44231406, 0.31810784, 0.0219766 , 0.26560092],
       [0.35609825, 0.43394185, 0.29022237, 0.18508144, 0.44186248,
        0.46321255, 0.49263477, 0.43161846, 0.33761462, 0.44432289],
       [0.06368299, 0.41256164, 0.40067093, 0.02089083, 0.43886369,
        0.49312767, 0.27891653, 0.37150429, 0.31498274, 0.42755167],
       [0.38593383, 0.07143022, 0.4982906

In [19]:
#7: compute the singular value decomposition of A
#7.1: plot the singular values
u,s,vh = np.linalg.svd(A)
s

array([5.05139818, 1.53151318, 1.28242955, 1.1767482 , 0.95873402,
       0.7255476 , 0.54317814, 0.42110255, 0.17749486, 0.07838178])

In [45]:
#7.2: reconstruct A' by using only the top 5 singular values
np.dot(u * np.diag(s), vh)

array([[ 0.2250952 ,  0.24159299,  0.48534992,  0.24401762,  0.35076581,
         0.27589447,  0.36349477,  0.35789454,  0.33224018,  0.43030713],
       [ 0.32627841, -0.14062561,  0.06895433,  0.02318169, -0.16676832,
        -0.23955395,  0.28429021,  0.19890109, -0.11512953, -0.20979896],
       [ 0.02471671,  0.02947006,  0.08413812, -0.09544784,  0.02165639,
         0.02869525, -0.05583868,  0.02128345, -0.03206106, -0.05207959],
       [ 0.04871042, -0.37944919,  0.20547748,  0.14110284, -0.06001504,
        -0.05471529, -0.29873114,  0.05289793, -0.00276015,  0.17026665],
       [ 0.00760223, -0.03668968, -0.04561168,  0.00825834,  0.05234583,
         0.06698449,  0.01481528,  0.03635888, -0.10645699,  0.01720813],
       [ 0.01660292, -0.02571628,  0.07796577,  0.02728072,  0.12704901,
        -0.07132092,  0.05314122, -0.17510514, -0.05770167, -0.01019271],
       [ 0.0143202 ,  0.00431087, -0.02642337, -0.00514149,  0.0435046 ,
        -0.03541316, -0.02250685,  0.02271814